#!/bin/bash
### ---
### name: 'set_fq'
### outputs:
### - 'tut25.fastq.gz'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf -- $exit_status > /Users/feargusogorman/workspace/PATH40060/bioinf/tutorial_25/work/b2/962ae5f084d7c8599a93ac84f49b55/.exitcode
    set +u
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /Users/feargusogorman/workspace/PATH40060/bioinf/tutorial_25/work/b2/962ae5f084d7c8599a93ac84f49b55/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f run-25-002-Control-1_spai.fq
    rm -f run-25-002-Control-1_spaj.fq
    rm -f run-25-002-Control-1_spag.fq
    rm -f run-25-002-Control-1_spaa.fq
    rm -f run-25-002-Control-1_spab.fq
    rm -f run-25-002-Control-1_spac.fq
    rm -f run-25-002-Control-1_spah.fq
    rm -f run-25-002-Control-1_spae.fq
    rm -f run-25-002-Control-1_spaf.fq
    rm -f run-25-002-Control-1_spad.fq
    ln -s /Users/feargusogorman/workspace/PATH40060/bioinf/tutorial_25/work/c2/a577a49447149b282c9d1c68e80da8/split/run-25-002-Control-1_spai.fq run-25-002-Control-1_spai.fq
    ln -s /Users/feargusogorman/workspace/PATH40060/bioinf/tutorial_25/work/c2/a577a49447149b282c9d1c68e80da8/split/run-25-002-Control-1_spaj.fq run-25-002-Control-1_spaj.fq
    ln -s /Users/feargusogorman/workspace/PATH40060/bioinf/tutorial_25/work/c2/a577a49447149b282c9d1c68e80da8/split/run-25-002-Control-1_spag.fq run-25-002-Control-1_spag.fq
    ln -s /Users/feargusogorman/workspace/PATH40060/bioinf/tutorial_25/work/c2/a577a49447149b282c9d1c68e80da8/split/run-25-002-Control-1_spaa.fq run-25-002-Control-1_spaa.fq
    ln -s /Users/feargusogorman/workspace/PATH40060/bioinf/tutorial_25/work/c2/a577a49447149b282c9d1c68e80da8/split/run-25-002-Control-1_spab.fq run-25-002-Control-1_spab.fq
    ln -s /Users/feargusogorman/workspace/PATH40060/bioinf/tutorial_25/work/c2/a577a49447149b282c9d1c68e80da8/split/run-25-002-Control-1_spac.fq run-25-002-Control-1_spac.fq
    ln -s /Users/feargusogorman/workspace/PATH40060/bioinf/tutorial_25/work/c2/a577a49447149b282c9d1c68e80da8/split/run-25-002-Control-1_spah.fq run-25-002-Control-1_spah.fq
    ln -s /Users/feargusogorman/workspace/PATH40060/bioinf/tutorial_25/work/c2/a577a49447149b282c9d1c68e80da8/split/run-25-002-Control-1_spae.fq run-25-002-Control-1_spae.fq
    ln -s /Users/feargusogorman/workspace/PATH40060/bioinf/tutorial_25/work/c2/a577a49447149b282c9d1c68e80da8/split/run-25-002-Control-1_spaf.fq run-25-002-Control-1_spaf.fq
    ln -s /Users/feargusogorman/workspace/PATH40060/bioinf/tutorial_25/work/c2/a577a49447149b282c9d1c68e80da8/split/run-25-002-Control-1_spad.fq run-25-002-Control-1_spad.fq
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /Users/feargusogorman/workspace/PATH40060/bioinf/tutorial_25/work/b2/962ae5f084d7c8599a93ac84f49b55/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
